### ISSUE TITLE
Phase Shift Gate

### ISSUE THREAD

**Issue by seankdecker** [att-innovate/squanch#3]
Hi Ben!

Maybe it would be beneficial to add the phase shift gate to the provided gates!

Such as:
```
_0 = np.array([[1, 0],[0, 0]])
_1 = np.array([[0, 0],[0, 1]])
def Phi(qubit, angle):
	'''
	Applies the single qubit phase shift operator to the specified qubit, updating the qsystem state.
    '''
	gate = _0 + np.exp(1j * angle) * _1
	qubit.qsystem.apply(expand(gate, qubit.index, qubit.qsystem.num_qubits, "Phi" + str(angle / np.pi)))
```
Or even an interface that allows for easily programmable gates!

If you are too busy to add them I'd be happy to add these

Thanks

**Comment by bencbartlett** [comment]
I've actually already added PHASE and CPHASE gates to the next version; I'll be committing that shortly before I finish the whitepaper. Thanks for the suggestion though!

**Comment by seankdecker** [comment]
Oh good to hear!
